---
- hosts: all
  become: true
  gather_facts: yes
  connection: ssh

  vars:
    remote_user: remote_user

  tasks:
  - name: Update package list
    apt:
      update_cache: yes
      cache_valid_time: 86400

  - name: Upgrade installed packages
    apt:
      upgrade: yes
      state: present

  - name: Remove unused packages and dependencies
    apt:
      autoremove: yes
